import type { EvidencePolicy } from "./types";

export const DEFAULT_MAX_DIFF_LENGTH = 100_000;

/**
 * Conservative defaults: only common textual/code extensions are accepted, and
 * environment files, private keys, credential files, and credential directories are
 * always rejected. A file without a listed extension is rejected rather than guessed.
 */
export const DEFAULT_EVIDENCE_POLICY: EvidencePolicy = {
  maxDiffLength: DEFAULT_MAX_DIFF_LENGTH,
  allowedExtensions: [
    ".ts",
    ".tsx",
    ".mts",
    ".cts",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".json",
    ".jsonc",
    ".md",
    ".mdx",
    ".txt",
    ".yaml",
    ".yml",
    ".toml",
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".html",
    ".htm",
    ".vue",
    ".svelte",
    ".py",
    ".rb",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".kts",
    ".scala",
    ".cs",
    ".php",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".hpp",
    ".cxx",
    ".hh",
    ".swift",
    ".dart",
    ".lua",
    ".r",
    ".ex",
    ".exs",
    ".erl",
    ".sh",
    ".bash",
    ".zsh",
    ".fish",
    ".ps1",
    ".bat",
    ".cmd",
    ".sql",
    ".graphql",
    ".gql",
    ".proto",
    ".tf",
    ".hcl",
    ".xml",
    ".svg",
    ".csv",
    ".tsv",
    ".diff",
    ".patch",
  ],
  deniedFileNames: [
    ".env",
    ".envrc",
    ".netrc",
    "_netrc",
    ".npmrc",
    ".pypirc",
    ".pgpass",
    ".git-credentials",
    ".htpasswd",
    ".dockercfg",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials",
    "credentials.json",
    "credentials.yaml",
    "credentials.yml",
    "secrets",
    "secrets.json",
    "secrets.yaml",
    "secrets.yml",
    "shadow",
    "master.key",
  ],
  deniedExtensions: [
    ".pem",
    ".key",
    ".p12",
    ".pfx",
    ".pkcs12",
    ".jks",
    ".keystore",
    ".ppk",
    ".p8",
    ".der",
  ],
  deniedDirectoryNames: [".ssh", ".aws", ".gnupg", ".gpg", ".azure", ".kube", ".docker"],
};
